/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    region: process.env.REACT_APP_REGION,
    Auth: {
        region: process.env.REACT_APP_REGION,
        userPoolId: process.env.REACT_APP_USER_POOL_ID,
        userPoolWebClientId: process.env.REACT_APP_USER_POOL_CLIENT_ID,
    },
    API: {
        region: process.env.REACT_APP_REGION,
        appSyncGraphqlEndpoint: process.env.REACT_APP_ENDPOINT,
        authenticationType: "AMAZON_COGNITO_USER_POOLS",
    },
};

export default awsmobile;